### ISSUE TITLE
Install with Adobe CC 2021 failes on OS X - new `ExManCmd` version needed

### ISSUE THREAD

**Issue by nros** [elements-storage/ZXPInstaller#72]
It seams as if the currently used Adobe Extension Manager command line utility 3.1.28 ([`ExManCmd`](../blob/master/app/bin/OSX/Contents/MacOS)) does not work with Adobe CC 2021. It fails to check the version of the installed programs, hence installing my extension always failed with error 403 (EXMAN_FAILED_NO_PRODUCT_SUPPORT_THIS_CEP).
This is the log from the extension manager on OS X (`less ~/Library/Application\ Support/Adobe/Extension\ Manager\ CC/Log/EMCL.log`):

```
02/02/21 16:38:51:510 | [ERROR] |  | ExManCmd | EMCL |  |  |  | 667968 | No products this CEP extension supports installed.
02/02/21 16:38:51:530 | [ERROR] |  | ExManCmd | EMCL |  |  |  | 667968 | Failed initial installation attempt, reinitializing product list, status = -403!
02/02/21 16:38:51:872 | [WARN] |  | ExManCmd | EMCL |  |  |  | 667968 | Failed to get version from file path "/Applications/Adobe InDesign 2021"!
02/02/21 16:38:51:872 | [WARN] |  | ExManCmd | EMCL |  |  |  | 667968 | Failed to get version from file path "/Applications/Adobe Illustrator 2021"!
02/02/21 16:38:51:872 | [WARN] |  | ExManCmd | EMCL |  |  |  | 667968 | Failed to get version from file path "/Applications/Adobe Photoshop 2021"!
02/02/21 16:38:51:884 | [ERROR] |  | ExManCmd | EMCL |  |  |  | 667968 | Product list reinitialized - about to retry install
02/02/21 16:38:51:942 | [ERROR] |  | ExManCmd | EMCL |  |  |  | 667968 | No products this CEP extension supports installed.
```

A newer version 3.1.34 is available here: https://partners.adobe.com/exchangeprogram/creativecloud/support/exman-com-line-tool.html

I was able to install my extension with this one manually.

PS: Error codes are listed here : https://community.adobe.com/t5/exchange/every-exman-command-error-code-exmancmd-error-code-list/td-p/11386103

**Comment by ErinFinnegan** [comment]
ExManCmd 3.1.34 is out of date... we're up to 7.11.1:

- [http://www.adobe.com/go/ExManCmdWin](http://www.adobe.com/go/ExManCmdWin)
- [http://www.adobe.com/go/ExManCmdMac](http://www.adobe.com/go/ExManCmdMac)

The latest release is compatible with M1 processors.

**Comment by Eugeny** [comment]
Fixed in the latest release.
