### ISSUE TITLE
Installation failed because the extension is not compatible with the installed applications

### ISSUE THREAD

**Issue by zhanglianbo35** [elements-storage/ZXPInstaller#74]
this issue still exists, I use the latest ZXPInstaller, and want to install [bodymovin-extension](https://github.com/TelegramMessenger/bodymovin-extension). 

Adobe Photoshop Version: 21.0.0 20191018.r.37 2019/10/18: 614690fb487  x64
Operating System: Windows 10 64-bit

**Comment by nros** [comment]
Could it be the same issue as #72 - for Windows, too? Included `ExManCmd` is too old?

**Comment by zhanglianbo35** [comment]
> Could it be the same issue as #72 - for Windows, too? Included `ExManCmd` is too old?
I also tried it in Mac,  same issue.

**Comment by dwehrle** [comment]
Same issue for Windows for us.

**Comment by zawilliams** [comment]
Can confirm on macOS 10.15.7 and Adobe Premiere Pro 15. Seems to be an issue with 2021 versions of Adobe apps.

**Comment by fooditron** [comment]
Issue still exists with the latest ZXP installer and BodyMovin_5.7.8

**Comment by znap026** [comment]
I'm getting this issue with an extension I've made. its come back that on windows it can no longer be installed

**Comment by mayura33** [comment]
Any updates on this thread?

**Comment by bvkavya** [comment]
Any updates on this? I am also getting the same error.

**Comment by Eugeny** [comment]
Fixed in the latest release.
